modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = ""
logoFile = "random_motd_icon.png"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "random_motd.mixins.json"

[[dependencies.random_motd]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "SERVER"

[[dependencies.random_motd]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "SERVER"
