# Automatically build the project and run any configured tests for every push
# and submitted a pull request. This can help catch issues that only occur on
# certain platforms or Java versions and provides a first line of defense
# against bad commits.

name: Build

on:
  push:
    branches:
      - 'neoforge/**'
      - 'fabric/**'
  pull_request:
    branches:
      - 'neoforge/**'
      - 'fabric/**'

jobs:
  build:
    strategy:
      matrix:
        # Use Java 21 for 1.21.x, Java 17 for 1.20.x
        java: [17, 21]
        # Test on both Linux and Windows
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Make gradle wrapper executable
        if: runner.os != 'Windows'
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build --no-daemon

      - name: Capture build artifacts
        if: runner.os == 'Linux' && matrix.java == '21'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-java-${{ matrix.java }}
          path: build/libs/
